# Unique name for this workflow
name: Run Security checks

# Definition when the workflow should run
on:
    push:
        branches:
            - mo/security

# Jobs to be executed
jobs:
    security-check:
        runs-on: ubuntu-latest
        steps:
            # Setup Java SDK
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            # Install Salesforce CLI
            - name: Install Salesforce CLI
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
                  mkdir sfdx-cli
                  tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
                  ./sfdx-cli/install
            # Install Salesforce CLI Scanner
            - name: Install Salesforce CLI Scanner
              run: 'echo y | sfdx plugins:install @salesforce/sfdx-scanner'
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2
            # Run Salesforce CLI Scanner For Security checks
            - name: Scan For Security Exceptions
              run: 'sfdx scanner:run -c=Security -t=./force-app -f=json -v'

